version: '3.8'

services:
  mongodb:
    hostname: $MONGO_HOST
    image: "zcube/bitnami-compat-mongodb:5.0.17"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGODB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD