services:
  data-service:
    build:
      context: ./data-service
    ports:
      - "5000:5000"
    volumes:
      - messages:/data
    environment:
      - FLASK_ENV=development
    networks:
      - custom_network

  frontend-service:
    build:
      context: ./frontend-service
    ports:
      - "3000:3000"
    environment:
      # - REACT_APP_BACKEND_URL=http://localhost:5000  # Backend service URL
      - REACT_APP_BACKEND_URL=http://localhost:5000  # Backend service URL
    depends_on:
      - data-service
    networks:
      - custom_network

volumes:
  messages:

networks:
  custom_network:
    driver: bridge