version: '3.8'

services:
  db:
    hostname: $MONGO_HOST
    image: "zcube/bitnami-compat-mongodb:5.0.17"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGODB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MONGO_URI: "mongodb://$MONGO_ROOT_USERNAME:$MONGODB_ROOT_PASSWORD@$MONGO_HOST:27017/"
    volumes:
      - .:/app
    networks:
      - my_network

volumes:
  mongo_data:
    driver: local

networks:
  my_network:
    driver: bridge